-- TABLA MOVIMIENTOS
CREATE TABLE MOVIMIENTOS(
    ID_OPERACION NUMBER(12,0) PRIMARY KEY,
    FECHA_OPERACION DATE,
    EMISOR VARCHAR2(300),
    RECEPTOR VARCHAR2(300),
    TIPO_OPERACION VARCHAR2(100),
    MONTO NUMBER(12,2)
);

ALTER TABLE MOVIMIENTOS MODIFY FECHA_OPERACION NOT NULL;
ALTER TABLE MOVIMIENTOS MODIFY EMISOR NOT NULL;
ALTER TABLE MOVIMIENTOS MODIFY RECEPTOR NULL;
ALTER TABLE MOVIMIENTOS MODIFY TIPO_OPERACION NOT NULL;
ALTER TABLE MOVIMIENTOS MODIFY MONTO NOT NULL;

-- SECUENCIA
CREATE SEQUENCE GLOBAL_SEQ
START WITH 1
INCREMENT BY 1
CACHE 20;

--TRIGGER
CREATE OR REPLACE TRIGGER MOVIMIENTOS_ID
BEFORE INSERT ON MOVIMIENTOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_OPERACION IS NULL THEN 
        :NEW.ID_OPERACION := GLOBAL_SEQ.NEXTVAL;
    END IF;
END;



