INSERT INTO MOVIMIENTOS (FECHA_OPERACION, EMISOR, RECEPTOR, TIPO_OPERACION, MONTO)
VALUES(TO_DATE('30/12/2024 22:35:59','DD/MM/YYYY HH24:MI:SS'),'BCP - INVERSIONES ESENCIA ANDINA','SERGIO MANUEL SUTTA PINEDO','TE YAPEARON',500);
INSERT INTO MOVIMIENTOS (FECHA_OPERACION, EMISOR, RECEPTOR, TIPO_OPERACION, MONTO)
VALUES(TO_DATE('31/12/2024 18:27:54','DD/MM/YYYY HH24:MI:SS'),'BCP - INVERSIONES ESENCIA ANDINA','SERGIO MANUEL SUTTA PINEDO','TE YAPEARON',500);
